spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: finance
    password: finance
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  modulith:
    events:
      jdbc:
        enabled: true

server:
  port: 8080